name: Clear History

on:
  workflow_dispatch:
    inputs:
      branch_to_delete:
        description: 'Name of the branch to delete'
        required: true

jobs:
  branch-actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch all branches and tags
      run: git fetch --prune --unshallow --tags

    - name: List branches for debugging
      run: git branch -a

    - name: Validate branch name
      run: |
        branch_to_delete=${{ github.event.inputs.branch_to_delete }}
        branches=$(git branch -a | grep -E "remotes/origin/$branch_to_delete$")
        if [ -z "$branches" ]; then
          echo "Error: Branch '$branch_to_delete' does not exist."
          exit 1
        fi

    - name: Create temporary orphan branch
      run: |
        selected_branch=${{ github.event.inputs.branch_to_delete }}
        git checkout -b temp_branch $selected_branch
        git checkout --orphan temp_branch
        git commit --allow-empty -m "Create temporary orphan branch based on $selected_branch"

    - name: Delete previous branch
      run: |
        git branch -D ${{ github.event.inputs.branch_to_delete }}

    - name: Rename orphan branch
      run: |
        git branch -m ${{ github.event.inputs.branch_to_delete }}

    - name: Push changes
      run: |
        git push origin ${{ github.event.inputs.branch_to_delete }} -f
